### ISSUE TITLE
BSASeq.csv

### ISSUE THREAD

**Issue by walleyResearch** [dblhlx/PyBSASeq#12]
The package is really good.  If possible, please can you include a section in the README that lists what the headings are in the BSASeq.csv table.

highbulk.AvgLD	
lowbulk.AvgLD	
sSV	
totalSV	
sSV/totalSV	
Threshold_sSV	
GS	
Threshold_GS	
DAF	
DAF_CI_LB	
DAF_CI_UB	
Threshold_DAF	
pvalue_tt	
Significance_SSV	
Significance_GS	
Significance_AF	
Significance_TT

**Comment by dblhlx** [comment]
Thanks very much for your feedback. I will do that soon.

**Comment by dblhlx** [comment]
Done.

**Comment by walleyResearch** [comment]
Thank you – much appreciated!
Have a good day.

Best wishes,
Peter

Dr Peter Glen Walley
Lecturer in Genetics
Crop Genetic Improvement Group Leader
Department of Biochemistry, Cell, and Systems Biology
Institute of Systems, Molecular & Integrative Biology
University of Liverpool | Liverpool | L69 7ZB | United Kingdom
Tel: +44 (0)151 794 9867

https://www.liverpool.ac.uk/systems-molecular-and-integrative-biology/

[signature_801010606]

Genetics Society Local Ambassador for University of Liverpool
Ask me about student membership | www.genetics.org.uk<http://www.genetics.org.uk> | @GenSocUK<https://twitter.com/GenSocUK?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>



From: dblhlx ***@***.***>
Date: Wednesday, 24 April 2024 at 13:49
To: dblhlx/PyBSASeq ***@***.***>
Cc: Walley, Peter ***@***.***>, Author ***@***.***>
Subject: Re: [dblhlx/PyBSASeq] BSASeq.csv (Issue #12)

Caution: This email originated from outside of the University. Do not click links or open attachments unless you recognise the source of this email and know the content is safe. Check sender address, hover over URLs and don't open suspicious email attachments.

Done.
