### ISSUE TITLE
Create exception for ZeroDivisionError

### ISSUE THREAD

**Issue by FleurGaBru** [dblhlx/PyBSASeq#14]
Hello!

We found some unexpected behaviour in the PyBSAseq script. When setting a window size that is too small, meaning that there are windows that do not contain any SNPs, PyBSAseq fails with the following error:

![image](https://github.com/dblhlx/PyBSASeq/assets/23460229/f8132861-3ba8-43e6-902f-af83f4a6587a)

It seems like unexpected behaviour that the pipeline fails, when windows contain no SNPs.
Would it be possible for you to create an exception for this error and e.g. infer the value "0"  for the ratio sSV / total SV in the effected windows?

Thanks a lot for your help in advance!

Kind regards,
Fleur

**Comment by dblhlx** [comment]
I'll take a look and let you know soon. BTW, micromamba is much faster than conda.

**Comment by dblhlx** [comment]
Hi Fleur:

I will fix the script in a couple of day. Please let me know if you are in hurry.

Jianbo

**Comment by dblhlx** [comment]
Hi Fleur:

I just modified the script. Please test it and let me know if encounter any issue.

Thanks,

Jianbo

**Comment by FleurGaBru** [comment]
Thank you so much! I will test it asap and give you feedback.

**Comment by FleurGaBru** [comment]
The message that you closed the message reminded me that I promised feedback. Thank you! 
We tested pyBSAseq with several projects after you introduced the fix. For most projects it run fine. However, we found the following issues:
 
- In sliding_windows.csv of some projects we see that some windows get a deltaAF value above the significance threshold but do not contain any SNPs. This is confusing and causes issues in our downstream analysis
- We discovered a "blocky" peak pattern in the PyBSAseq plot that appears with smaller window sizes after you introduced the fix. We think that this might be related to the way how you impute the ratio value for windows without SNPs
 
We tried to dive into your code and we can see that you introduced an if/else statement in lines 1172-1175. Could you please explain how you define sub_l[2] and if this could cause the above described issues?

**Comment by dblhlx** [comment]
I'll take a look and get back to you soon.

Lines 1172-1175 are involved in calculating sliding window-specific thresholds, they shouldn't have other effects.

**Comment by FleurGaBru** [comment]
Any news on this issue? If you need any more information from me, please let me know. Happy to help.

**Comment by dblhlx** [comment]
Sorry for the late reply. I have been working on a grant proposal lately. We just submitted today.

I can reproduce the "blocky peaks" issue. I just removed SVs from a large genomic region to create many empty sliding windows in this region. The "blocky peaks" is caused by the way I deal with a stretch of empty sliding windows: I assume that adjacent sliding windows have very similar allele frequency, G-statistic value, and sSV/totalSV ratio. I just sign the values of these three parameter of the previous non-empty sliding window to the empty sliding window. I thought about other ways, e.g., gradually increase/decrease, but it is more complex to implement, so I used the simplest way in dealing with the situation.

However, I couldn't reproduce your first issue. It would be much easy if I can use your data. A sub-dataset containing only a single chromosome or a chromosomal segment of ~10 megabases with the peak in the middle should work fine. Please let me know if it's okay for you.

You can reopen this issue if you like.

**Comment by FleurGaBru** [comment]
Thanks for your reply and the explanation. Just to let you know that we are creating a test dataset for you at the moment. I hope to come back with it in about a week. Good luck with your proposals!

**Comment by FleurGaBru** [comment]
Hi, thanks for your patience! My slow replies are certainly not lack of interest but very much lack of time. I highly appreciate your efforts to help us. Hereby the description of an example where we found intervals without SNPs but with a high significance value.

Used PyBSAseq command: ` python PyBSAseq.py -i example-data-test1.tsv -o example-data-no-snps-in-interval -p F2 -b 18,18 -v 0.01,0.01 -s 500000,2000`
 
Returned the following plots:
![image001](https://github.com/user-attachments/assets/079b89c1-ac78-4437-86a8-490071903612)

The significant interval is created using an in-house parser because Delta_AF > DAF_CI_UB was TRUE (sliding_windows.csv).

interval |	CHROM |	min_interval |	max_interval |	win_count |	g_count |	delta_count |	max_g_statistic |	max_snp_index |	interval_name |
-|-|-|-|-|-|-|-|-|-|
0 |	1 |	chr1 |	11514001	| 11626001 |	56 |	0 |	56 |	8.165.071 |	0.478901

In the example-data-test1.tsv there are no snps in the window 11514001-11626001
 
```text
chr1      11459872          C           T            168.96 C/T        9,9        99              C/T        14,6      99
chr1      11512385          G           A            153.061             G/A        3,9        99              G/A        6,18      99
chr1      11646323          A            C           1240.97             C/C       0,20      99              C/C       0,19      99
chr1      11653177          C           T            385.325             C/T        11,4      99              C/T        5,12      99
```
 
Part of the sliding_windows.csv file is attached. Please let me know in case you need anything else to look into this problem.

[sliding_windows.csv](https://github.com/user-attachments/files/17958370/sliding_windows.csv)

[example-data-test1.txt](https://github.com/user-attachments/files/17958386/example-data-test1.txt)

**Comment by dblhlx** [comment]
Thanks very much for your update!
I am away from my computers now, will take a look after returning to my office on the coming Monday.

**Comment by dblhlx** [comment]
The start point of the sliding window is 11514001,  and the size of a sliding window is 500000 according the -s option in the command line, so the range of the sliding window is between 11514001 and 12014000. There are 7 SVs within this region in the input file, two of them are not real SVs (positions 11646323 and 11776223), so this sliding window contains 5 valid SVs.
