### ISSUE TITLE
Non-numeric contig IDs aren't tolerated

### ISSUE THREAD

**Issue by zkstewart** [dblhlx/PyBSASeq#4]
Hi,

In the process of running this software, I have run into the below error.

```
ValueError: invalid literal for int() with base 10: 'NC_052499.1'
```

I've changed the code as a workaround i.e.,

```
#peaklst = sorted(peaklst, key = lambda x: (int(x[0]), int(x[1])))
peaklst = sorted(peaklst, key = lambda x: (x[0], int(x[1])))
```

It might be nice if it supported non-numeric contig IDs by default though. Regardless, I thought I'd bring this to attention in case anyone else has a similar problem.

**Comment by dblhlx** [comment]
I rewrote the chromosome sorting code. It can handle chromosome names with both digits and letters.
