### ISSUE TITLE
Help needed in error resolution

### ISSUE THREAD

**Issue by fawadhassan** [dblhlx/PyBSASeq#5]
Hi I am using PyBSASeq lib for my research but continuously running into this error
[eoor.pptx](https://github.com/dblhlx/PyBSASeq/files/12148421/eoor.pptx)
[error.docx](https://github.com/dblhlx/PyBSASeq/files/12148431/error.docx)

**Comment by dblhlx** [comment]
Sorry to reply so late. GitHub notification setup is really not straightforward. I just changed the notification configuration. Hope it can notify me new issues and comments.

Please run the script with the test data on this website first. Please let me know if you encounter the same issue. Please send me a piece of your data (~1000 rows) if the script works fine with the test data.
