### ISSUE TITLE
Running PyBSAseq without interactive input

### ISSUE THREAD

**Issue by jd3234** [dblhlx/PyBSASeq#6]
Hi,

first thanks for this great tool! It has been very helpful and easy to use in contrast to some other BSAseq tools out there :)
We would like to use PyBSAseq as part of a fully automated pipeline and the interactive input is hindering us a little bit. Would there be a possibility to switch that behavior off or make it optional?
In our case the data comes preprocessed so that we have only chromosomes we want to use in the input and the order is also correct.

Thanks!

**Comment by dblhlx** [comment]
Thanks very much for the nice words.

I will add an option to disable the interactive mode. I'll let you know once I made the change.

**Comment by jd3234** [comment]
Sounds great! Thanks!

**Comment by dblhlx** [comment]
I modified the script PyBSASeq_WP.py. By default, users will not be asked to input the chromosome names. I tested using the test datasets and it worked. Please test it and let me know if encounter any problems.
