### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by jd3234** [dblhlx/PyBSASeq#7]
Hi again,

I noticed that you have no license file in your repository. In your publication you have selected the MIT license:

![image](https://github.com/dblhlx/PyBSASeq/assets/32764481/7ae62d14-4383-450e-b10c-59aaf429691c)

If you need an example here is one from the freebayes variant caller repo (also MIT): https://github.com/freebayes/freebayes/blob/master/LICENSE

**Comment by dblhlx** [comment]
Thanks for the link.

We are considering to switch to GPL license. Please let me know if the proposed license change prevents you using this software.

**Comment by jd3234** [comment]
A GPL license would be great as well! Thanks!

**Comment by jd3234** [comment]
Thanks for adding the license! I am closing the issue :)
