### ISSUE TITLE
test files

### ISSUE THREAD

**Issue by adriludwig** [dblhlx/PyBSASeq#8]
Hi!
I want to test the program to understand how it works and what are the outputs.  So, I'll use one of the files that you provided to test. I'm just wondering which are the values for these parameters: -p popstrct -b fbsize,sbsize . Thanks very much!

**Comment by dblhlx** [comment]
popstrct indicates the type of the population from which the bulks are selected, it be F2 (F2 population), RIL (recombinant inbred line), or BC (backcross population), the default is F2.
fbsize,sbsize indicates the sizes of the first and the second bulks.
It you construct the bulks using an F2 population, and the first bulk contains 50 individuals while the second bulk contains 70 individuals, the command should be as below (assume you are in the working directory and the working directory contains the python script and the input files):
python PyBSASeq.py  -i parents.csv,bulks.csv -p F2 -b 50,70
